create table public.user(
    id int generated by default as identity,
    username text not null,
    fullname text not null,
    email text not null,
    passwords text not null,
    tweet text,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    deleted_At timestamp with time zone
);

alter table only public.user
    add constraint user_pkey primary key(id);



insert into public.user (username, fullname, email, passwords, tweet) values ('blablabla','kambing ganteng','great@you.com','apajaya','hallo twotter');
insert into public.user (username, fullname, email, passwords, tweet) values ('mikean','mike andrew','grea@you.com','apa','hallo twetter');
insert into public.user (username, fullname, email, passwords, tweet) values ('muhars','muh arsalan','gre@you.com','apaja','hallo twatter');
insert into public.user (username, fullname, email, passwords, tweet) values ('bebeng','ben grosse','gr@you.com','apaya','hallo twutter');
insert into public.user (username, fullname, email, passwords, tweet) values ('johhny','jonny mark','g@you.com','jaya','hallo twottar');
insert into public.user (username, fullname, email, passwords, tweet) values ('danlos','daniel','greats@you.com','paja','hallo twettir');
insert into public.user (username, fullname, email, passwords, tweet) values ('harhar','harry haris','greatss@you.com','aja','hallo twattur');
insert into public.user (username, fullname, email, passwords, tweet) values ('isagu','isa the iguana','greatsss@you.com','aya','hallo twuttor');